remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
minima:
  skin: auto

show_downloads: true

title: VELOSOFIZE

header_pages:
  - /en/index.md
  - /bg/about.md
  - /en/for_contributors.md
