remote_theme: "jekyll/minima@1e8a445"
plugins:
- jekyll-remote-theme
minima:
  skin: auto

show_downloads: false

title: VELOSOFIZE

header_pages:
  - /en/index.md
  - /bg/about.md
  - /en/for_contributors.md
